global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'hiringgo'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['hiringgo:8080']
        labels:
          application: "HiringGo"
